server:
  port: 8091
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easymusic?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#项目目录
project:
  folder: /Users/cyt/projects/i/cache/easymusic
  #日志级别配置
log:
  root:
  level: debug
#管理员账号
admin:
  account: admin
  password: admin123

management:
  health:
    redis:
      enabled: false